### ISSUE TITLE
Change of ownership before archiving the projet

### ISSUE THREAD

**Issue by merwan** [allo-media/elm-es-simple-query-string#11]
Hi @n1k0,
Would you (or someone else trustful in the Elm community) be interested in taking ownership of this project?
If this is not of interest, I will archive the project.

There are other open-source projects that we will happily give back to other maintainers: https://github.com/allo-media?q=&type=public&language=elm. Feel free to pass the information around you!

**Comment by n1k0** [comment]
Hey @merwan, thanks for reaching out. I'm not interested in taking over these projects, but I really appreciate you asked. Cheers.

**Comment by merwan** [comment]
Thanks for your quick answer.
As I don't know people in the Elm community, I archive this project.
