### ISSUE TITLE
Browser tab freezing with a recursive query

### ISSUE THREAD

**Issue by BeardedBear** [allo-media/elm-es-simple-query-string#6]
When we paste this query : `(poil | champignon | chapeau (poil | champignon | chapeau (poil | champignon | chapeau (poil | champignon | chapeau (poil | champignon | chapeau (poil | champignon | chapeau (poil | champignon | chapeau) ))))))`, browser tab freeze.

**Comment by fbentz** [comment]
I closed this issue, because it's not the parser, but rendering function.
